name: Pull request into main

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node modules
        run: npm ci

      - name: Prettier
        run: npm run prettier:check

      # - name: Jest
      #   run: npm run test

      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}

      # - run: |
      #     set -e
      #     curl -Os https://uploader.codecov.io/latest/linux/codecov
      #     find . -iregex "codecov.*"
      #     chmod +x codecov
      #     ./codecov -t ${CODECOV_TOKEN}
      #     rm codecov
